var docs = {
  'align-content': {
    'en': '<p>Aligns a flex container\'s lines within the flex container when there is extra space on the cross-axis.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'bn': '<p>যদি cross-axis এ অতিরিক্ত যায়গা থাকে তাহলে flex container লাইন গুলোকে কে flex container এর ভিতরেই সারিবদ্ধ করে।</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'af': '<p>Rig die flex houer se lyne binne die flex houer wanneer daar ekstra spasie is op die kruis-as. </p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (verstek)</code>',
    'he': '<p>יישור שורות בתוך ה-flex כשיש מקום מיותר בציר המשני.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'ro': '<p>Aliniază liniile unui container flex cu containerul flex cand există spațiu în plus pe axa transversală.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'bg': '<p>Подравнява реводете на flex контейнера вътре в него ако има допълнително място по вртикалата.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'de': '<p>Richtet die Zeilen innerhalb eines flex-Containers aus, wenn auf der Querachse Platz ist.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'pt-br': '<p>Alinha as linhas dentro de um container flex quando há espaço sobrando no eixo cruzado.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'es': '<p>Alinea las líneas de un contenedor flex cuando exista más espacio en el eje transversal.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'fr': '<p>Aligne les lignes d\'un conteneur flex à l\'intérieur du conteneur flex quand il y a de l\'espace superflu sur l\'axe transversal.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'ru': '<p>Выравнивает ряды flex-контейнера внутри него (работает только, если элементы расположены больше чем в один ряд).</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'fa': '<p>فرض کنید که ارتفاع flex-container بیشتر از فضایی است که flex-lineها گرفته اند و اصطلاحا مقداری فضای خالی در flex-container وجود دارد. به کمک خاصیت align-content شما می‌توانید محل قرارگیری این flex-line ها را مشخص کنید که از نظر محور عمودی در کجا قرار گیرند.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'zh-cn': '<p>当交叉轴有多余空间时，对齐容器内的轴线。</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'zh-tw': '<p>當交叉軸有多餘空間時，對齊容器內的軸線。</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'tr': '<p>Eğer cross-axis\'de fazladan alan varsa, flex container satırlarını flex container\'ın içinde hizalar.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'az': '<p>Əgər cross-axis\'də artıq sahə varsa, flex container sətirlərini flex container\'in içində nizamlayar.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'it': '<p>Allinea le linee all\'interno di un contenitore flex se c\'è spazio extra lungo l\'asse verticale </p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'ko': '<p>세로선 상에 여분의 공간이 있는 경우 Flex 컨테이너 사이의 간격을 조절합니다.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'lt': '<p>Lygiuoja elastiško supančio elemento eilutes, kai kertančios ašies atžvilgiu yra laisvos vietos.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'vi': '<p>Sắp xếp các dòng trong hộp chứa khi có thêm không gian dọc theo trục ngang.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'pl': '<p>Wyrównuje wiersze wewnątrz kontenera z atrybutem flex w przypadku gdy na osiach poprzecznych jest dodatkowe miejsce.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'cs': '<p>Určuje zarovnání řádků ve směru vedlejší osy, pokud je v kontejneru přebytek místa.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'ja': '<p>直行軸 (cross axis) に余裕がある場合、コンテナー内の行を配置します。</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'hu': '<p>A flex konténer sorvonalait igazítja a flex konténeren belül, amennyiben van szabad tér a másodlagos kereszttengely mentén.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'eo': '<p>Vicigas la liniojn de la fleksujo tie kie estas aldona spaco sur la transversakso.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'sv': '<p>Justerar en flex-containers rader inom flex-containern när det finns extra utrymme på motsata axeln.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'uk': '<p>Вирівнює рядки flex-контейнеру всередені самого flex-контейнеру, коли є додатковий простір на поперечній осі.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'hi': '<p>यह कंटेनर के भीतर रखी वस्तुओं के मध्य की जगह को संरेखित करता है।</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'gj': '<p>જ્યારે flex કન્ટેનરમાં cross-axis પર વધારાની જગ્યા હોય ત્યારે flex કન્ટેનરની લાઈનોને ગોઠવે છે.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'sr': '<p>Поравњава редове у флекс контејнеру када постоји вишак простора дуж попречне осе.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'bs': '<p>Poravnava redove u fleks kontejneru kada postoji višak prostora duž poprečne ose.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'hr': '<p>Poravnava redove u fleks kontejneru kada postoji višak prostora duž poprečne osi.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'nl': '<p>Lijnt de lijnen van een flex container binnen de flex container uit waneer er extra plaats is op de dwarsas.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'ta': '<p>குறுக்கு அச்சு மீது கூடுதல் இடம் இருக்கும் போது flex container-ல் வரிகளை சீரமைக்கும்.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'te': '<p>క్రాస్-యాక్సిస్‌లో అదనపు స్థలం ఉన్నప్పుడు ఫ్లెక్స్ కంటైనర్‌లోని పంక్తులను సమలేఖనం చేస్తుంది. </p><code>flex-start</code><code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'ml': '<p>ക്രോസ്-അച്ചുതയിൽ അധിക സ്ഥലം ഉള്ളപ്പോൾ ഫ്ലെക്സസ് കണ്ടെയ്നറിലുള്ള നിരകൾ വിന്യസിക്കുന്നു. </p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'el': '<p>Ευθυγραμμίζει τις γραμμές ενός flex container μέσα στο πλαίσιο του flex container όταν υπάρχει επιπλέον χώρος στον εγκάρσιο άξονα.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'mk': '<p>Ги подредува линиите на flex контејнерот кога во него има дополнителнен простор по вертикалната оска.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'lv': '<p>Novieto flex-elementu robežas flex-konteinera iekšienē.(Darbojas tikai, ja ir pieejama papildus vieta uz šķērsojošās ass.)</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'id': '<p> Selaraskan garis flex di dalam wadah flex apabila ada ruang tambahan pada sumbu silang </p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'ar': '<p>محاذاة سطور حاويات فكلس في داخل حاوية فلكس عندما يكون هناك مساحة اضافية على المحور الثانوي .</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'ca': '<p>Alinea les línees d\'un contenidor flex quan existeixi més espai en l\'eix transversal.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'da': '<p>Justerer en flex-containers linjer inden i flex-containeren når der er plads til overs på den tværgående akse.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'et': '<p>Joondab flex konteineri jooned flex konteineriga kui on piisavalt ruumi ristteljel.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'fi': '<p>Kohdistaa rivit flex-säilössä, jos poikittaisakselilla on ylimääräistä tilaa.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (oletusarvo)</code>',
    'gl': '<p>Aliña as liñas dun contedor flex cando hai espazo extra no eixe transversal.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>stretch</code>',
    'th': '<p>จัดเรียงบรรทัดภายใน flex container ในกรณีที่มีพื้นที่ว่างบนแกนขวาง</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'mn': '<p>Хөндлөн тэнхлэгт нэмэлт зай байгаа үед flexbox-н мөрүүдийг дураараа байрлуулна.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'sk': '<p>Zarovná riadky kontajnera flex v rámci kontajnera flex, ak je na priečnej osi extra priestor.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'si': '<p>හරස් අක්‍ෂයේ අමතර ඉඩ ඇති විට flex කන්ටේනරය තුළ පේළි ඇසිරීම තීරණය කරයි.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
    'np': '<p>फ्लेक्स कन्टेनरमा थप ठाउँ हुँदा फ्लेक्स कन्टेनरको रेखाहरूलाई क्रस-एक्सिसमा मिलाउनको लागि प्रयोग गरिन्छ।</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code> <code>stretch (default)</code>',
  },
  'align-items': {
    'en': '<p>Aligns flex items along the cross axis.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'bn': '<p>flex item গুলোকে cross axis বরাবর সারিবদ্ধ করে।</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'af': '<p>Rig flex items op die kruis-as.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (verstek)</code>',
    'he': '<p>יישור פריטים ב-flex לאורך הציר המשני.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'ro': '<p>Aliniază elementele flex de-a lungul axei transversale.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'bg': '<p>Подрежда flex елементите по дължината на осите.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'de': '<p>Richtet die flex-Elemente entlang der Querachse aus.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'pt-br': '<p>Alinha itens flex ao longo do eixo cruzado.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'es': '<p>Alinea elementos Flex a lo largo del eje transversal.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'fr': '<p>Aligne les éléments flex selon l\'axe transversal.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'ru': '<p>Выравнивает flex-элементы вдоль пересекаемой оси.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'fa': '<p>این خاصیت نحوه چینش Flex itemها را در محور Cross مشخص می کند. این خاصیت مانند justify-content  است تنها تفاوت آنها در مقادیرشان است.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'zh-cn': '<p>在交叉轴上对齐多个元素</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'zh-tw': '<p>在交叉軸上對齊多個元素</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'tr': '<p>Flex öğelerini cross-axis boyunca hizalar.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'az': '<p>Flex elementlərini cross-axis boyunca nizamlayar.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'it': '<p>Allinea gli elementi flex lungo l\'asse verticale</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'ko': '<p>Flex 요소를 세로선 상에서 정렬합니다.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'lt': '<p>Lygiuoja elastiškus elementus palei kertančią ašį.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'vi': '<p>Sắp xếp các hạng mục flex dọc theo trục ngang.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'pl': '<p>Wyrównuje elementy z atrybutem flex wzdłuż osi poprzecznych.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'cs': '<p>Určuje zarovnání všech prvků ve směru vedlejší osy.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'ja': '<p>アイテムを直行軸 (cross axis) に沿って配置します。</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'hu': '<p>A másodlagos kereszt-tengely mentén igazítja a flex elemeket.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'eo': '<p>Vicigas transversakse fleksajn erojn.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'sv': '<p>Justerar flex-objekt längs med motsata axeln.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'uk': '<p>Вирівнює flex-елементи вздовж перетинної осі.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'hi': '<p>वस्तुओं को उर्ध्वाधर रूप से संरेखित करता है।</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'gj': '<p>flex itemsને cross axisના સમાંતર ગોઠવે છે.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'sr': '<p>Поравњава флекс елементе дуж попречне осе.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'bs': '<p>Poravnava fleks elemente duž poprečne ose</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'hr': '<p>Poravnava fleks elemente duž poprečne osi</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'nl': '<p>Lijnt flex elementen uit over de dwarsas.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'ta': '<p>குறுக்கு அச்சு வழியாக உருப்படிகளை ஒழுங்குபடுத்துகிறது.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'te': '<p> క్రాస్ యాక్సిస్ వెంట ఫ్లెక్స్ అంశాలను సమలేఖనం చేస్తుంది. </p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'ml': '<p>ക്രോസ്സ് അക്ഷത്തിൽ വളവുതിരിവുകളുള്ള ഇനങ്ങൾ വിന്യസിക്കുന്നു. </p> <code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'el': '<p>Ευθυγραμμίζει αντικείμενα flex κατά μήκος του εγκάρσιου άξονα.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'mk': '<p>Ги подредува flex елементите по вертикалната оска.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'lv': '<p>Novieto flex vienības attiecībā pret šķērsojošo asi.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'id': '<p> Sejajarkan item fleksibel di sepanjang sumbu silang. </p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'ar': '<p>محاذاة عناصر فلكس على طول المحور الثانوي.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'ca': '<p>Alinea elements Flex al llarg de l\'eix transversal.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'da': '<p>Justerer flex-elementer langs den tværgående akse.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'et': '<p>Joondab flex elemendid mööda risttelge.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'fi': '<p>Kohdistaa flex-elementit poikittaisakselin suuntaisesti.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (oletusarvo)</code>',
    'gl': '<p>Aliña os elementos flex no eixe transversal.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'th': '<p>จัดเรียง flex items ตามแกนขวาง</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'mn': '<p>Хөндлөн тэнхлэгийн дагуу flex items-г байрлуулна.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'sk': '<p>Zarovná ohybné prvky pozdĺž priečnej osi.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'si': '<p>හරස් අක්ෂය දිගේ flex අයිතම පෙළගස්වයි.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
    'np': '<p>फ्लेक्स आइटमहरूलाई क्रस-एक्सिसमा मिलाउँछ।</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch (default)</code>',
  },
  'align-self': {
    'en': '<p>Aligns a flex item along the cross axis, overriding the <code>align-items</code> value.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'bn': '<p><code>align-items</code> এর মান না মেনে cross axis বরাবর একটি flex item কে সারিবদ্ধ করে।</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'af': '<p>Rig `n flex item op die kruis-as, en oorskryf die <code>align-items</code> waarde.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'he': '<p>יישור פריט flex ספציפי לאורך הציר המשני, דורס את ההגדרה של <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'ro': '<p>Aliniază un element flex de-a lungul axei transversale, suprascriind valoarea proprietății <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'bg': '<p>Подрежда flex елемент по дължината на осите, презаписвайки <code>align-items</code> стойността.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'de': '<p>Richtet die flex-Elemente entlang der Querachse aus und überschreibt den Wert von <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'pt-br': '<p>Alinha um item flex ao longo do eixo cruzado, substituindo o valor de <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'es': '<p>Alinea un elemento flex a lo largo del eje transversal, anulando el valor de <code>align-items</code></p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'fr': '<p>Aligne un élément flex selon l\'axe transversal, outrepassant la valeur de <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'ru': '<p>Выравнивает flex-элемент вдоль пересекаемой оси, перекрывая значения свойства <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'fa': '<p>با استفاده از این خاصیت می‌توانید نحوه قرار گرفتن عمودی هر flex item را مشخص کنید. مقادیر این خاصیت دقیقا همان مقادیر خاصیت align-items است. <code>align-items</code> value.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'zh-cn': '<p>在交叉轴上对齐一个元素，覆盖<code>align-items</code>所设定的值.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'zh-tw': '<p>在交叉軸上對齊一個元素，覆蓋<code>align-items</code>所设定的值.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'tr': '<p><code>align-items</code>\'ın değerini ezerek, sadece bu öğeyi cross-axis boyunca hizalar</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'az': '<p><code>align-items</code>\'ın dəyərini üstələyərək, sadəcə bu elementi cross-axis boyunca nizamlayar</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'it': '<p>Allinea un elemento flex lungo l\'asse verticale, sovrascrive il valore di <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'ko': '<p>지정된 <code>align-items</code> 값을 무시하고 Flex 요소를 세로선 상에서 정렬합니다.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'lt': '<p>Lygiuoja elastišką elementą palei kertančią ašį nepaisant <code>align-items</code> reikšmės.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'vi': '<p>Sắp xếp một hạng mục flex dọc theo trục ngang, ghi đè lên giá trị của <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'pl': '<p>Wyrównuje element z atrybutem flex wzdłuż osi poprzecznych nadpisując wartość właściwości <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'cs': '<p>Určuje zarovnání prvku ve podle vedlejší osy, přebíjí hodnotu <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'ja': '<p>アイテムを直行軸 (cross axis) に沿って配置します。<code>align-items</code>の値を上書きします。</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'hu': '<p>A másodlagos kereszttengely mentén igazít egy flex elemet, felülírva a <code>align-items</code>-ben megadott értéket.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'eo': '<p>Vicigas transversakse fleksajn elementojn, anstataŭigante la <code>align-items</code> valoron.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'sv': '<p>Justerar ett flex-objekt längs med motsata axeln, överskrider värdet från <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'uk': '<p>Вирівнює flex-елемент вздовж перетинної осі, перекриваючи значення властивості <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'hi': '<p>छैतिज रूप से किसी विशिष्ट वस्तु के लिए नियम प्रदान करता है, <code>align-items</code> के नियमों को न मानते हुए।</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'gj': '<p>flex itemને  cross axisના સમાંતર ગોઠવે છે અને <code>align-items</code>ની valueને બદલી નાખે છે. .</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'sr': '<p>Поравњава појединачни флекс елемент дуж попречне осе надјачавајући вредност <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'bs': '<p>Poravnava pojedinačni fleks element duž poprečne ose nadjačavajući vrijednost</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'hr': '<p>Poravnava pojedinačni fleks element duž poprečne osi nadjačavajući vrijednost</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'nl': '<p>Lijnt een flex element uit over de dwarsas, en overschrijft de waarde van <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'ta': '<p><code>align-items</code> மதிப்புகளை புறக்கணித்து, குறுக்கு அச்சு வழியாக உருப்படிகளை ஒழுங்குபடுத்துகிறது.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'te': '<p><code>align-item</code> విలువను అధిగమించి, క్రాస్ యాక్సిస్ వెంట ఒక ఫ్లెక్స్ ఐటెమ్‌ను సమలేఖనం చేస్తుంది. ముగింపు <code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'ml': '<p><code>align-items</code> ഇനെ അസാധു ആക്കി കൊണ്ട്, ക്രോസ്സ് അക്ഷത്തിൽ ഒരു ഫ്ലെക്സ് ഇനത്തെ വിന്യസിക്കുന്നു</p></p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'el': '<p>Ευθυγραμμίζει ένα αντικείμενο flex κατά μήκος του εγκάρσιου άξονα, παρακάμπτοντας την αξία του <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'mk': '<p>Подредува flex element по вертикалната оска, презапишувајќи ја <code>align-items</code> вредноста.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'lv': '<p>Novieto flex vienību attiecībā pret šķērsojošo asi, pārrakstot <code>align-items</code> vērtību.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'id': '<p> Sejajarkan item fleksibel di sepanjang sumbu silang yang menimpa objek <code>align-items</code> value.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'ar': '<p>محاذاة عنصر فلكس على طول المحور الثانوي, متجاوزا قيمة <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'ca': '<p>Alinea un element flex al llarg de l\'eix transversal, anul·lant el valor de <code>align-items</code></p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'da': '<p>Justerer et flex-element langs den tværgående akse, og underkender værdien af <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'et': '<p>Joondab flex elemendi mööda risttelge, ja võtab üle <code>align-items</code> väärtuse.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'fi': '<p>Kohdistaa yksittäisen flex-elementin poikittaisakselin suuntaisesti ohittaen <code>align-items</code>-ominaisuudelle määritetyn arvon.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'gl': '<p>Aliña un elemento flex no eixe transversal, sobrescribindo o valor de <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'th': '<p>จัดเรียง flex item ตามแกนขวาง, โดยทับค่าของคำสั่ง <code>align-items</code></p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'mn': '<p><code>align-items</code> утгыг дарж, flex item-г хөндлөн тэнхлэгийн дагуу байрлуулна.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'sk': '<p>Zarovná prvok flex pozdĺž krížovej osi, pričom nahradí hodnotu <code>align-items</code>.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'si': '<p><code>align-items</code> හි අගය නොසලකා හැර හරස් අක්ෂය දිගේ flex අයිතමය පෙළගස්වයි.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
    'np': '<p>फ्लेक्स आइटमलाई क्रस-एक्सिसमा मिलाउँछ, <code>align-items</code> को मानलाई ओभरराइड गर्दै।</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>baseline</code> <code>stretch</code>',
  },
  'flex-direction': {
    'en': '<p>Defines the direction of the main axis.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'bn': '<p>Main axis এর দিক নির্ধারন করে।</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'af': '<p>Bepaal die direksie van die hoof as.</p><code>row (verstek)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'he': '<p>מגדיר את הכיוון של הציר הראשי.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'ro': '<p>Definește direcția axei principale.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'bg': '<p>Определя посоката на основната ос.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'de': '<p>Legt die Ausrichtung der Hauptachse fest.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'es': '<p>Define la dirección del eje principal.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'pt-br': '<p>Define a direção do eixo principal.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'fr': '<p>Définit la direction de l\'axe principal.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'ru': '<p>Задает направление основной оси.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'fa': '<p>جهت آیتم ها را مشخص می کند.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'zh-cn': '<p>定义主轴的方向。</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'zh-tw': '<p>定義主軸的方向。</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'tr': '<p>main axis\'in yönünü belirler.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'az': '<p>Main axis\'in yönünü təyin edər.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'it': '<p>Definisce la direzione dell\'asse principale</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'ko': '<p>정렬할 방향을 지정합니다.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'lt': '<p>Nustato pagrindinės ašies kryptį.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'vi': '<p>Xác định hướng của trục chính.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'pl': '<p>Określa kierunek głównej osi.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'cs': '<p>Určuje směr hlavní osy.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'ja': '<p>主軸 (main axis) の方向を指定します。</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'hu': '<p>Definiálja az elsődleges főtengely irányát.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'eo': '<p>Difinas la direkton de la ĉefa akso.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'sv': '<p>Definierar huvudaxelns håll.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'uk': '<p>Визначає напрямок головної осі.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'hi': '<p>मुख्य धुरी की दिशा परिभाषित करता है।</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'gj': '<p>main axisની દિશા નક્કી કરે છે .</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'sr': '<p>Одређује правац главне осе.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'bs': '<p>Određuje pravac glavne ose.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'hr': '<p>Određuje pravac glavne osi.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'nl': '<p>Definieert de richting van de hoofdas.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'ta': '<p>முக்கிய அச்சு திசையை வரையறுக்கிறது.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'te': '<p> ప్రధాన అక్షం యొక్క దిశను నిర్వచిస్తుంది. </p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'ml': '<p>പ്രധാന അക്ഷത്തിന്റെ ദിശ നിർവ്വചിക്കുന്നു.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'el': '<p>Ορίζει την κατεύθυνση του κύριου άξονα.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'mk': '<p>Ја одредува насоката на хоризонталната оска.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'lv': '<p>Nodefinē galvenās ass virzienu.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'id': '<p> Tentukan arah sumbu utama.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'ar': '<p>تحديد اتجاه المحور الرئيسي.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'ca': '<p>Defineix la direcció de l\'eix principal.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'da': '<p>Definerer hovedaksens retning.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'et': '<p>Määrab põhitelje suuna</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'fi': '<p>Määrittää pääakselin suunnan.</p><code>row (oletusarvo)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'gl': '<p>Define a dirección do eixe principal.</p><code>row</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'th': '<p>กำหนดทิศทางของแกนหลัก</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'mn': '<p>Үндсэн тэнхлэгийн чиглэлийг тодорхойлно.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'sk': '<p>Určuje smer hlavnej osi.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'si': '<p>ප්‍රධාන අක්‍ෂයේ දිශාව තීරණය කරයි.</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
    'np': '<p>मुख्य अक्षको दिशा परिभाषित गर्छ।</p><code>row (default)</code> <code>row-reverse</code> <code>column</code> <code>column-reverse</code>',
  },
  'flex-flow': {
    'en': '<p>Shorthand property for <code>flex-direction</code> and <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'bn': '<p><code>flex-direction</code> এবং <code>flex-wrap</code> এর জন্য একটি Shorthand property।</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'af': '<p>Kortskrif eienskap vir <code>flex-direction</code> en <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'he': '<p>קיצור בשביל <code>flex-direction</code> ו-<code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'ro': '<p>Scurtătura pentru <code>flex-direction</code> și <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'bg': '<p>Съкратена версия на <code>flex-direction</code> and <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'de': '<p>Kurzschreibweise für <code>flex-direction</code> und <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'pt-br': '<p>Propriedade abreviada para <code>flex-direction</code> e <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'es': '<p>Abreviación de las propiedades de <code>flex-direction</code> and <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code></p>',
    'fr': '<p>Raccourci pour <code>flex-direction</code> et <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'ru': '<p>Свойство для быстрой записи <code>flex-direction</code> и <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'fa': '<p>اکنون به کمک flex-flow شما می‌توانید مقادیری که برای <code>flex-direction</code> و <code>flex-wrap</code> در نظر دارید را در یک خاصیت بنویسید.</p>',
    'zh-cn': '<p><code>flex-direction</code>和<code>flex-wrap</code>的缩写性质。</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'zh-tw': '<p><code>flex-direction</code>和<code>flex-wrap</code>的縮寫性質。</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'tr': '<p><code>flex-direction</code> ve <code>flex-wrap</code> için kısa yazım özelliği.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'az': '<p><code>flex-direction</code> və <code>flex-wrap</code> üçün qısa yazım özəlliyi.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'it': '<p>Scorciatoia per le proprietà <code>flex-direction</code> e <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'ko': '<p>다음의 속성들을 간략히 한 속성입니다: <code>flex-direction</code> and <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'lt': '<p>Sutrumpinta komanda atstojanti <code>flex-direction</code> ir <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'vi': '<p>Viết tắt cho từ <code>flex-direction</code> và từ <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'pl': '<p>Skrócona wersja <code>flex-direction</code> i <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'cs': '<p>Zkrácená verze vlastností <code>flex-direction</code> a <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'ja': '<p><code>flex-direction</code>と<code>flex-wrap</code>のショートハンドプロパティーです。</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'hu': '<p>Rövidítésként szolgáló összevonása a <code>flex-direction</code> és a <code>flex-wrap</code> tulajdonságoknak.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'eo': '<p>Mallongita trajto por <code>flex-direction</code> kaj <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'sv': '<p>Kort version av <code>flex-direction</code> och <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'uk': '<p>Скорочена властивість для <code>flex-direction</code> та <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'hi': '<p>शोर्ट हैंड प्रॉपर्टी <code>flex-direction</code> एवं <code>flex-wrap</code> के लिए।</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'gj': '<p><code>flex-direction</code> અને <code>flex-wrap</code>ની બદલે વાપરી શકાય છે..</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'sr': '<p>Скраћено својство за <code>flex-direction</code> и <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'bs': '<p>Skraćeno svojstvo za <code>flex-direction</code> i <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'hr': '<p>Skraćeno svojstvo za <code>flex-direction</code> i <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'nl': '<p>Een verkorte eigenschap voor een combinatie van <code>flex-direction</code> en <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'ta': '<p><code>flex-direction</code> and <code>flex-wrap</code> இரண்டின் சுருக்கெழுத்து.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'te': '<p> <code>flex-direction</code> మరియు <code>flex-wrap</code> కోసం సంక్షిప్తలిపి ఆస్తి.</p><code>&lt;flex-direction &gt; &lt;flex-wrap &gt;</code>',
    'ml': '<p><code>flex-direction</code> and <code>flex-wrap</code> ോർട്ട്ഹാൻഡ്.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'el': '<p>Συντομογραφική ιδιότητα για τα <code>flex-direction</code> και <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'mk': '<p>Скратена верзија на <code>flex-direction</code> и <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'lv': '<p><code>flex-direction</code> un <code>flex-wrap</code> saīsināsinātā versija.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'id': '<p> Properti singkatan untuk <code>flex-direction</code> and <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'ar': '<p>خاصية مختصرة لـ <code>flex-direction</code> و <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'ca': '<p>Abreujament de les propietats de <code>flex-direction</code> and <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code></p>',
    'da': '<p>Forkortelse for <code>flex-direction</code> og <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'et': '<p>Lühendatud omadus, mis ühendab <code>flex-direction</code> ja <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'fi': '<p>Ominaisuuksien <code>flex-direction</code> ja <code>flex-wrap</code> yhdistelmä.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'gl': '<p>Propiedade-atallo para <code>flex-direction</code> e <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'th': '<p>เป็นคำสั่งย่อของ <code>flex-direction</code> และ <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'mn': '<p><code>flex-direction</code> болон <code>flex-wrap</code>-д зориулсан товчилсон проперти.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'sk': '<p>Skrátená vlastnosť pre <code>flex-direction</code> a <code>flex-wrap</code>.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'si': '<p><code>flex-direction</code> සහ <code>flex-wrap</code> සඳහා වන තනි ගුණාංගයකි.</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
    'np': '<p><code>flex-direction</code> र <code>flex-wrap</code> को लागि शॉर्टह्यान्ड प्रोपर्टी।</p><code>&lt;flex-direction&gt; &lt;flex-wrap&gt;</code>',
  },
  'flex-wrap': {
    'en': '<p>Specifies whether flex items are forced on a single line or can be wrapped on multiple lines.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'bn': '<p>flex item গুলোকে কি একই লাইনে থাকতে বাধ্য করা হবে নাকি একাধিক লাইনে wrap করা যাবে তা নির্ধারন করে।</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'af': '<p>Spesifiseer of die flex items op `n enkele lyn geforseer is of oor meerdere lyne gevou word.</p><code>nowrap (verstek)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'he': '<p>מציין אם פריטי flex יהיו בשורה אחת או יכולים להתפרס ("להעטף" - wrap) בכמה שורות.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'ro': '<p>Specifică daca elementele flex sunt forțate pe o singură linie sau pot fi impărțit pe mai multe linii.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'bg': '<p>Определя дали flex елементите са на един ред или могат да бъдат разпределени на много редове.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'de': '<p>Legt fest, ob die flex-Elemente in eine Zeile gezwängt werden oder auf mehrere Zeilen umgebrochen werden können.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'pt-br': '<p>Especifica se os itens flex são forçados em um linha única ou podem quebrar em múltiplas linhas.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'es': '<p>Especifica si los elementos flex son forzados a una sola línea o pueden ser envueltos en multiples líneas.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'fr': '<p>Spécifie si les éléments flex sont forcés à être sur une seule ligne ou peuvent être enveloppés sur plusieurs lignes.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'ru': '<p>Указывает, нужно ли чтоб элементы принудительно находились в одном ряду или автоматически переносились.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'fa': '<p>در حالت عادی همه flex item ها در یک خط قرار می‌گیرند. به کمک خاصیت flex-wrap شما می‌توانید مشخص کنید که flex item ها در چندین خط قرار بگیرند.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'zh-cn': '<p>定义flex元素必须在单行或自动换行成多行。</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'zh-tw': '<p>定義flex元素必須在單行或自動換行成多行。</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'tr': '<p>Flex öğelerin tek satıra sığmasını ya da çoklu satırlara bölünmesini belirler.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'az': '<p>Flex elementlərin tək sətirə sığmasını və ya çoxlu sətirlərə bölünməsini təyin edər.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'it': '<p>Specifica se gli elementi flex vengono disposti forzatamente su una singola linea o se possono occupare più linee</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'ko': '<p>Flex 요소들을 한 줄 또는 여러 줄에 걸쳐 정렬합니다.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'lt': '<p>Nusako ar elastiški elementai turi būti sutalpinti vienoje eilutėje, ar gali būti paskirstyti per kelias eilutes.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'vi': '<p>Xác định xem các hạng mục flex phải trên một dòng hoặc có thể quấn trên nhiều dòng.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'pl': '<p>Określa czy elementy z atrybutem flex muszą być ściśnięte w jednym wierszu czy mogą być rozproszone.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'cs': '<p>Určuje, zda budou prvky na jednom řádku, nebo se mohou rozdělit na více řádků.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'ja': '<p>アイテムを強制的に一行に並べるか、複数行へ折り返すかを指定します。</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'hu': '<p>Meghatározza, hogy a flex elemek egy sorba vannak kényszerítve vagy megtörhetnek több sorba.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'eo': '<p>Indikas ĉu fleksaj elementoj devige estu sur nura linio aŭ faldkapeblas je pluraj linioj.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'sv': '<p>Specificerar on flex-objekt är låsta till en rad eller om dom får flöda över till flera rader.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'uk': '<p>Визначає, чи будуть елементи знаходитись в одному рядку, чи будуть перенесені до наступних рядків.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'hi': '<p>यह निर्दिष्ठ करता है की कोई वस्तु एक पंक्ति अथवा कई पंक्तियों में आएगी।</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'gj': '<p>તે નક્કી કરે છે કે flex items ને single line માં wrap કરવા કે  multiple linesમાં .</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'sr': '<p>Одређује да ли ће флекс елементи стајати у једном реду или ће прећи у нове редове.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'bs': '<p>Određuje da li će fleks elementi stajati u jednom redu ili će preći u nove redove.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'hr': '<p>Određuje da li će fleks elementi stajati u jednom redu ili će prijeći u nove redove.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'nl': '<p>Specifieert of de flex elementen op een enkele lijn geforceerd worden, of ze over meerdere lijnen gewikkeld worden.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'ta': '<p>ஒரு ஒற்றை வரியில் பொருட்களை கட்டாயமாக்க வேண்டுமா அல்லது பல வரிகளில் மூடப்பட்டிருக்கலாம் என்பதைக் குறிப்பிடுகிறது.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'te': '<p>ఫ్లెక్స్ ఐటెమ్‌లు ఒకే పంక్తిలో బలవంతం చేయబడుతున్నాయా లేదా బహుళ పంక్తులలో చుట్టవచ్చా అని నిర్దేశిస్తుంది.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'ml': '<p>ഫ്ലെക്സിങ് ഇനങ്ങളെ ഒരൊറ്റ വരിയിൽ നിർബന്ധിതരാണോ അല്ലെങ്കിൽ ഒന്നിലധികം വരികളിൽ പൊതിഞ്ഞ് വരാമോ എന്ന് നിർദേശിക്കുന്നു.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'el': '<p>Προσδιορίζει κατά πόσο τα αντικείμενα flex στριμώχνονται σε μία γραμμή ή μπορούν να τυλιχθούν σε πολλαπλές γραμμές.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'mk': '<p>Специфицира дали flex елементите се присилени во еден ред или можат да бидат распределени во повеќе редови.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'lv': '<p>Norāda to, vai flex vienības tiek novietotas vienā rindā vai var tik izvietotas vairākās rindās.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'id': '<p> Tentukan apakah flex objek dipaksa pada satu garis atau dapat dibungkus pada beberapa baris.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'ar': '<p>تحديد اذا كانت عناصر فلكس يجب ان تكون في سطر واحد او ممكن ان تتمدد الى اكثر من سطر.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'ca': '<p>Especifica si els elements flex són forçats a una sola línia o poden ser encapçulats en multiples línies.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'da': '<p>Fastsætter om flex-elementer skal tvinges ind på en enkelt linje eller må fordeles over flere linjer.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'et': '<p>Täpsustab, kas flex elemendd on surutud on ühele reale või on nad pakitud mitmele reale.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'fi': '<p>Määrittää, pakotetaanko elementit yhdelle riville vai voivatko ne rivittyä useammalle riville.</p><code>nowrap (oletusarvo)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'gl': '<p>Determina se os elementos flex teñen que apertarse para coller nunha soa liña ou se se poden distribuír en múltiples liñas.</p><code>nowrap</code> <code>wrap</code> <code>wrap-reverse</code>',
    'th': '<p>กำหนดว่า flex items จะถูกบังคับให้อยู่ในบรรทัดเดียว หรือสามารถพับไปอยู่หลายบรรทัด</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'mn': '<p>Flex items-г нэг мөрөнд шахах эсвэл олон мөрөнд тарааж байрлуулах уу гэдгийг заана.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'sk': '<p>Určuje, či sa položky flex musia nachádzať na jednom riadku alebo môžu byť zabalené do viacerých riadkov.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'si': '<p>flex අයිතම තනි පේළියකට හෝ පේළි කිහිපයකට ඇසිරීම තීරණය කරයි.</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
    'np': '<p>फ्लेक्स आइटमहरूलाई एउटै लाइनमा बाध्य पार्ने वा धेरै लाइनहरूमा र्‍याप गर्न मिल्ने हो वा होइन भनेर निर्दिष्ट गर्दछ।</p><code>nowrap (default)</code> <code>wrap</code> <code>wrap-reverse</code>',
  },
  'justify-content': {
    'en': '<p>Aligns flex items along the main axis.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'bn': '<p>flex item গুলোকে main axis বরাবর সারিবদ্ধ করে।</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'af': '<p>Rig die flex items op die hoof as.</p><code>flex-start (verstek)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'he': '<p>יישור פריטי flex לאורך הציר הראשי.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'ro': '<p>Aliniază elementele flex de-a lungul axei principale.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'bg': '<p>Подрежда flex елементи по дължината на основната ос.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'de': '<p>Richtet die flex-Elemente entlang der Hauptachse aus.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'pt-br': '<p>Alinha os itens flex ao longo do eixo principal.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'es': '<p>Alinea los elementos flex a lo largo del eje principal.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'fr': '<p>Aligne les éléments flex selon l\'axe principal.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'ru': '<p>Выравнивает flex-элементы вдоль главной оси.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'fa': '<p>با استفاده از این خاصیت می‌توانید نحوه چیدمان آیتم‌ها بر روی محور اصلی را تعیین کنید (به یاد داشته باشید همانطور که گفتیم اگر خاصیت flex-direction برابر column یا column-reverse باشد، محور اصلی عمودی خواهد بود).</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'zh-cn': '<p>将flex元素和主轴对齐。</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'zh-tw': '<p>將flex元素和主軸對齊。</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'tr': '<p>Flex öğeleri main axis boyunca hizalar.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'az': '<p>Flex elementləri main axis boyunca nizamlayar.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'it': '<p>Allinea gli elementi flex lungo l\'asse principale.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'ko': '<p>Flex 요소들을 가로선 상에서 정렬합니다.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'lt': '<p>Lygiuoja elastiškus elementus palei pagrindinę ašį.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'vi': '<p>Sắp xếp các hạng mục flex dọc theo trục chính.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'pl': '<p>Wyrównuje elementy z atrybutem flex wzdłuż głownej osi.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'cs': '<p>Zarovnává prvky ve směru hlavní osy.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'ja': '<p>アイテムを主軸 (main axis) に沿って配置します。</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'hu': '<p>Az elsődleges főtengely mentén igazítja a flex elemeket.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'eo': '<p>Liniigas fleksajn elementojn laŭĉefakse.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'sv': '<p>Justerar flex-objekt längs med huvudaxeln.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'uk': '<p>Вирівнює flex-елементи вздовж головної осі.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'hi': '<p>वस्तुओं को छैतिज रूप से संरेखित करता है।</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'gj': '<p>flex itemsને main axisની સમાંતર ગોઠવે છે.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'sr': '<p>Поравњава флекс елементе дуж главне осе.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'bs': '<p>Poravnava fleks elemente duž glavne ose.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'hr': '<p>Poravnava fleks elemente duž glavne osi.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'nl': '<p>Lijnt de flex elementen uit langs de hoofdas.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'ta': '<p>முக்கிய அச்சில் உருப்படிகளை சீரமைக்கும்.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'te': '<p>ప్రధాన అక్షంతో పాటు ఫ్లెక్స్ అంశాలను సమలేఖనం చేస్తుంది.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'ml': '<p>ഫ്ലെക്സി ഇനങ്ങളെ മെയിൻ ആക്സിസിൽ വിന്യസിക്കുന്നു</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'el': '<p>Ευθυγραμμίζει αντικείμενα flex κατά μήκος του κύριου άξονα.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'mk': '<p>Подредува flex елементи по хоризонталната оска.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'lv': '<p>Novieto flex vienību attiecībā pret galveno asi.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'id': '<p> Sejajarkan flex objek pada sepanjang sumbu utama. </p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'ar': '<p>محاذاة عناصر فلكس على طول المحور الرئيسي.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'ca': '<p>Alinea els elements flex al llarg de l\'eix principal.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'da': '<p>Justerer flex-elementer langs hovedaksen.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'et': '<p>Joondab flex elemendid mööda põhitelge.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'fi': '<p>Kohdistaa flex-elementit pääakselin suuntaisesti.</p><code>flex-start (oletusarvo)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'gl': '<p>Aliña os elementos flex no eixe principal.</p><code>flex-start</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code>',
    'th': '<p>จัดเรียง flex items ตามแกนหลัก</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'mn': '<p>Үндсэн тэнхлэгийн дагуу flex item-ийг байрлуулна.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'sk': '<p>Zarovnanie prvkov flex pozdĺž hlavnej osi.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'si': '<p>ප්‍රධාන අක්ෂය දිගේ flex අයිතම පෙළගස්වයි.</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
    'np': '<p>फ्लेक्स आइटमहरूलाई मुख्य अक्षमा मिलाउँछ।</p><code>flex-start (default)</code> <code>flex-end</code> <code>center</code> <code>space-between</code> <code>space-around</code> <code>space-evenly</code>',
  },
  'order': {
    'en': '<p>Specifies the order of the flex item.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'bn': '<p>Flex item এর order (ক্রম) নির্ধারন করে।</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'af': '<p>Spesifiseer die orde van die flex item.</p><code>&lt;integer&gt; (... -1, 0 (verstek), 1, ...)</code>',
    'he': '<p>מציין את הסדר של פריט flex.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'ro': '<p>Specifică ordinea elementelor flex.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'bg': '<p>Определя реда на flex елемента.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'de': '<p>Legt die Reihenfolge der flex-Elemente fest.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'pt-br': '<p>Especifica a ordem de um item flex.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'es': '<p>Especifica el orden de los elementos flex.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'fr': '<p>Spécifie l\'ordre de l\'élément flex.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'ru': '<p>Указывает порядок flex-элемента.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'fa': '<p>به کمک خاصیت order شما می‌توانید ترتیب چینش Flex itemها را مشخص کنید. مقادیر این خاصیت اعداد می‌باشند و هرچه عدد کوچکتر باشد اولویت آیتم بالاتر خواهد بود..</p><code>(... -1, 0 (default), 1, ...) &lt;integer&gt;</code>',
    'zh-cn': '<p>决定flex元素的顺序。</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'zh-tw': '<p>決定flex元素的順序。</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'tr': '<p>Flex öğenin sırasını belirler.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'az': '<p>Flex elementinin sırasını təyin edər.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'it': '<p>Specifica l\'ordine degli elementi flex</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'ko': '<p>Flex 요소의 순서를 지정합니다.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'lt': '<p>Nusako elastiškų elementų eilės tvarką.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'vi': '<p>Chỉ rõ thứ tự của các hạng mục flex</p><code>&lt;itegeer&gt;(... -1, 0 (default), 1, ...) </code>',
    'pl': '<p>Określa kolejność elementów z atrybutem flex.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'cs': '<p>Určuje pořadí prvku v kontejneru.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'ja': '<p>アイテムの順序を指定します。</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'hu': '<p>Meghatározza a flex elem sorrendiségét.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'eo': '<p>Precizigas la ordon de la fleksa elemento.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'sv': '<p>Specificerar ordningen för flex-objekten.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'uk': '<p>Вказує порядок flex-елементу.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'hi': '<p>फ्लेक्स आइटम का क्रम निश्चित करता है।</p><code>&lt;पूर्णांक&gt; (... -1, 0 (default), 1, ...)</code>',
    'gj': '<p>flex itemનો ક્ર્મ નક્કી કરે છે.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'sr': '<p>Дефинише место појединачног флекс елемента.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'bs': '<p>Definira mjesto pojedinog fleks elementa.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'hr': '<p>Definira mjesto pojedinog fleks elementa.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'nl': '<p>Bepaalt de volgorde van de flex elementen.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'ta': '<p>உருப்படியின் வரிசையைக் குறிப்பிடுகிறது.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'te': '<p>ఫ్లెక్స్ ఐటెమ్ యొక్క క్రమాన్ని పేర్కొంటుంది. </p><code>&lt; పూర్ణాంకం&gt; (... -1, 0 (default), 1, ...)</code> ',
    'ml': '<p>ഫ്ളക്സ് ഇനങ്ങളുടെ ക്രമം വ്യക്തമാക്കുന്നു</p></p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'el': '<p>Προσδιορίζει την σειρά του αντικειμένου flex.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'mk': '<p>Го одредува редоследот на flex елементот.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'lv': '<p>Norāda flex vienības kārtas numuru.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'id': '<p> Tentukan urutan flex objek.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'ar': '<p>تحديد ترتيب عناصر فلكس.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'ca': '<p>Especifica l\'ordre dels elements flex.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'da': '<p>Fastsætter rækkefølgen af flex-elementet.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'et': '<p>Täpsustab flex elemendi järjekorda.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'fi': '<p>Määrittää yksittäisen flex-elementin järjestyksen.</p><code>&lt;integer&gt; (... -1, 0 (oletusarvo), 1, ...)</code>',
    'gl': '<p>Especifica a orde do elemento flex.</p><code>&lt;integer&gt; (... -1, 0, 1, ...)</code>',
    'th': '<p>กำหนดลำดับของ flex item</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'mn': '<p>Flex item-н байрлах дарааллыг заана.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'sk': '<p>Určuje poradie položky flex.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'si': '<p>flex අයිතමයේ අනුපිළිවෙල තීරණය කරයි.</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
    'np': '<p>फ्लेक्स आइटमको क्रम निर्दिष्ट गर्दछ।</p><code>&lt;integer&gt; (... -1, 0 (default), 1, ...)</code>',
  }
};
